# Generated by Django 2.0.7 on 2018-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('board_title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('hit', models.IntegerField(default=0)),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Modify Date')),
            ],
        ),
    ]
